export const shopCategories = [
    { value: 'fashion', label: 'Fashion' },
    { value: 'electronics', label: 'Electronics' },
    { value: 'groceries', label: 'Groceries' },
    { value: 'beauty', label: 'Beauty & Personal Care' },
    { value: 'home_decor', label: 'Home & Decor' },
    { value: 'sports', label: 'Sports & Fitness' },
    { value: 'toys', label: 'Toys & Games' },
    { value: 'books', label: 'Books' },
    { value: 'automotive', label: 'Automotive' },
    { value: 'pet_supplies', label: 'Pet Supplies' },
    { value: 'jewelry', label: 'Jewelry' },
    { value: 'stationery', label: 'Stationery' },
    { value: 'garden', label: 'Garden & Outdoor' },
    { value: 'baby_products', label: 'Baby Products' },
    { value: 'furniture', label: 'Furniture' },
    { value: 'health', label: 'Health & Wellness' },
    { value: 'footwear', label: 'Footwear' },
    { value: 'kitchen', label: 'Kitchen Appliances' },
];
